# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    deploy-image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Add .env file
              run: echo "${{ secrets.ENVIROMENT_VARIABLES }}" >> .env

            - name: Build & push Dockerfile image
              uses: mr-smithers-excellent/docker-build-push@v6
              with:
                  image: hdang09/hotel-be
                  tags: v1, latest
                  registry: docker.io
                  dockerfile: Dockerfile
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

    pull-image:
        runs-on: self-hosted
        needs: deploy-image

        steps:
            - name: Stop and remove the current container
              run: |
                  sudo docker stop hotel-be || true
                  sudo docker rm hotel-be || true
            - name: Pull the latest image
              run: sudo docker pull hdang09/hotel-be
            - name: Start Docker image
              run: sudo docker run --name hotel-be -d -p 5000:5000 hdang09/hotel-be
